### PR TITLE
Removed isNonEmptyPlan from the Plan() method of the Executor interface #1029

### PR DESCRIPTION
**Pull request by Jyoti050402**

### CODE REVIEW

**Comment by motatoes** [comment]
Thanks for the PR could you explain why you have removed this segment to write a file on empty plan? This feature is used by a few who want to create custom workflows only on nonempty plan status like for checkov

**Comment by motatoes** [comment]
Since you are addressing #1029 I have sent you some further details on what was meant by the PR

**Comment by motatoes** [comment]
@Jyoti050402 any reason you have removed all those docs files ?

**Comment by Jyoti050402** [comment]
> @Jyoti050402 any reason you have removed all those docs files ?

@motatoes not sure why it is happening, while commiting it was showing that docs file have been deleted but I can see the docs files in my editor and in my forked repository even after pushing the changes.

**Comment by ZIJ** [comment]
@Jyoti050402 massive thanks for the PR! Your contribution means a lot.

Could you please clean it up so that only relevant changes are included?
Your commit [6031acca](https://github.com/diggerhq/digger/pull/1043/commits/6031acca6956eff1596b0c78e1dd3c64d09b87f5) does in fact delete those docs files. One way to fix it is to create new branch off the latest develop and redo your changes on top of it as fresh commits, then create a new pr. There are also other ways to achieve the same.

Also, please use descriptive names for commits and add a meaningful description to the PR; "changes have been made" unfortunately does not allow others to understand what has been changed. One convention you could use is [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

Also, please provide a meaningful description of your changes in the PR. Otherwise the reviewer needs to deduce the reasons behind the proposed changes from code, which is much harder and prone to misunderstanding.

**Comment by motatoes** [comment]
@Jyoti050402 any luck getting the docs commit removed ?

**Comment by motatoes** [comment]
Hey @Jyoti050402 I'm closing this PR for now, if you are able to fix the dox deletion issue will happily merge it with the interface change. Let me know if you manage to keep the docs folder intact :)

**Pull request closed without merging**
