### PR TITLE
Add AllowDraftPRs flag, disabled by default

### PR DESCRIPTION
**Pull request by ri-roee**
Not tested yet in E2E flow, only in go testing

### CODE REVIEW

**Comment by motatoes** [comment]
Thanks! I believe this is related to #1195 if I am not mistaken

**Comment by ri-roee** [comment]
@motatoes any chance you could test this locally? I can't seem to get my local stack up

**Comment by ri-roee** [comment]
Bump! :)

**Review by motatoes — APPROVED** [review]
just tested in https://github.com/diggerhq/test-digger-draft-disable with the flag and it seems to be working fine!

**Pull request merged**
